# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energydata',
            name='Waktu',
            field=models.DateTimeField(max_length=1000),
        ),
    ]
