# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-30 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibration', models.FloatField(blank=True, default=None, null=True)),
                ('coordinate_x', models.FloatField(blank=True, default=None, null=True)),
                ('coordinate_y', models.FloatField(blank=True, default=None, null=True)),
                ('coordinate_z', models.FloatField(blank=True, default=None, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=250)),
                ('node_id', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='node_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landslide.NodeID'),
        ),
    ]
