# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-21 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landslide', '0002_remove_nodeid_node_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='tanggal',
            field=models.DateField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='waktu',
            field=models.TimeField(db_index=True, default=None, null=True),
        ),
    ]
