# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-11 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('student_id', models.CharField(max_length=64)),
                ('university_id', models.CharField(max_length=64)),
            ],
        ),
    ]
