# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-11 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
    ]
