# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-08 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=640)),
                ('no_telp', models.CharField(max_length=640)),
                ('alamat', models.CharField(max_length=640)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tegangan', models.CharField(max_length=1000)),
                ('energy', models.CharField(max_length=1000)),
                ('arus', models.FloatField(blank=True, default=None, null=True)),
                ('frekuensi', models.CharField(max_length=1000)),
                ('total_energy', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(db_index=True, default=None, null=True)),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.Customer')),
            ],
        ),
    ]
