# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-08 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='energydata',
            name='waktu',
            field=models.TimeField(db_index=True, default=None, null=True),
        ),
    ]
