# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-08 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_energydata_waktu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energydata',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='energydata',
            name='tanggal',
            field=models.DateField(db_index=True, default=None, null=True),
        ),
    ]
