# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-18 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Node_number', models.CharField(max_length=10)),
                ('Tegangan', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Energy', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('Arus', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('Frekuensi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Total_energy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Waktu', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
