# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energy',
            name='Node_ID',
            field=models.CharField(max_length=10000, primary_key=True, serialize=False),
        ),
    ]
