# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0004_auto_20171025_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energy',
            name='Node_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
