# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0006_auto_20171025_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energy',
            name='Node_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nodeenergy',
            name='Arus',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='nodeenergy',
            name='Energy',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='nodeenergy',
            name='Frekuensi',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='nodeenergy',
            name='Tegangan',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='nodeenergy',
            name='Total_energy',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='nodeenergy',
            name='Waktu',
            field=models.CharField(max_length=1000),
        ),
    ]
